### ISSUE TITLE
dir is piboy-configurator2 but scripts ref piboy-configurator

### ISSUE THREAD

**Issue by weclock-droid** [Vilikt/PiBoy-Configurator2#2]
title - 
basically this script is unusable because trying to run anything from it references a directory that doesn't exist.

**Comment by Vilikt** [comment]
Please look at the readme. You need to precise the folder name when you execute "git clone" command.

> cd /home/pi
> git clone https://github.com/Vilikt/PiBoy-Configurator2.git ./PiBoy-Configurator
> cd PiBoy-Configurator
> sudo python install.py

Or just rename your folder : mv ./PiBoy-Configurator2 ./PiBoy-Configurator
